
name: Bug Report
description: Create a bug report for SKJade.
title: ' '
labels: bug
assignees: ''
body:
  - type: input
    attributes:
      label: What version of SKJade are you using?
      description: 'For example: v1.20. Don't just say "latest".'
    validations:
      required: true
  - type: input
    attributes:
      label: What type of server are you using?
      description: 'For example: Paper, Tunity, Vannilla, etc.'
    validations:
      required: true
    - type: input
    attributes:
      label: Reproduceable
      description: 'How can we recreate this bug?'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your issue
      description: Describe the problem you're seeing, anything else you think was missed above.
    validations:
      required: true
    - type: input
    attributes:
      label: Expected Behavior
      description: 'What did you expect to happen?'
    validations:
      required: true
